### ISSUE TITLE
mysql autoincrement not translated to postgresql syntax

### ISSUE THREAD

**Issue by Dimi727** [oscarfonts/mysql-workbench-to-postgres#5]
Hi,

thanks for the script! I saw one thing for autoincrementing primary keys. In mysql there is an extra statement (  `id` INT NOT NULL AUTO_INCREMENT) , in postgres an incrementing primary key is marked as SERIAL and not ID only to activate autoincrement ( "id" SERIAL NOT NULL).

**Comment by oscarfonts** [comment]
Would you be able to submit a Pull Request?

**Comment by Dimi727** [comment]
Hey, I didnt have time to work on it yet. Just wanted to mention for the moment.
